.TH BSSH 1 "24 Jan 2023" "version 2023.01.24"

.SH NAME
BSSH \- a wrapper for Bitwarden CLI and ssh-agent

.SH SYNOPSIS
BSSH [ -hvpt ] [ssh key name]

.SH DESRIPTION
BSSH quickly activates ssh keys by name, filling passwords via Bitwarden CLI, and
adding them to ssh-agent. Keys are activated for 1-hour at a time.

The ssh key name provided to
.B BSSH
will be used to look up both the key itself and the password for the key. If
that key has a password,
.B BSSH
will search Bitwarden for an entry named `SSH: [ssh key name]' and autofill the
password with the results. If that entry is not found, `[ssh key name]' will
also be attempted before giving up on a password search. The key will be passed
to the ssh-agent regardless.

.SH OPTIONS
.TP
.B -h
Shows simple help.
.TP
.B -v
Shows current version number.
.TP
.B -p [pattern prefix]
Set Bitwarden prefix pattern for the title search. The default pattern is
`SSH:'. If your key is named `testkey', then the default pattern will search
`SSH: testkey' in Bitwarden for the key password.

This is the same as setting `pattern_prefix' in the configuration file.
.TP
.B -t [type]
Set the SSH key type to test for. By default
.B BSSH
will search for `id_ed25519', `id_dsa`, and `id_rsa` in that order.

This is the same as setting `key_types' in the configuration file.

.SH CONFIGURATION FILE
.TP
.I $XDG_CONFIG_HOME/bssh/config
Configuration settings in this file will override default settings. Each
setting is a string that should be written as `NAME="VALUE"'. Valid settings
are `pattern_prefix', `key_locations', and `key_types'

.SH ENVIRONMENT VARIABLES
Environment variables will override the default settings and any configuration
file settings.
.TP
.B SSH_KEY_LOCATIONS
List of folders containing ssh keys.

This environment variable can contain any number of folder paths, space
separated, which will be used to search for the ssh keys. The folders are
searched in order and the search stops at the first successful match.

Unless otherwise defined, this variable defaults to ~/.ssh/

This is the same as setting `key_locations' in the configuration file.
.TP
.B BW_PASSWORD
Bitwarden master password (optional). If set, this environment variable will be
used to automatically authenticate your bitwarden session. Alternatively,
a file at $XDG_CONFIG_HOME/Bitwarden CLI/bw.pass containing the password will
provide the same functionality. If neither exist the user will be prompted for
the password.

.SH EXAMPLES
If you have an ssh key located at ~/.ssh/work/id_rsa, it can be loaded by
entering:

$ BSSH work

.SH DEPENDENCIES
.TP
.B bw
The Bitwarden CLI client
.TP
.B expect
programmed dialogue with interactive programs

.SH AUTHOR
James Tomasino
